### ISSUE TITLE
CrunchbaseAPIException 

### ISSUE THREAD

**Issue by Sebastian-ehrig** [FahadNoor/py_crunchbase#8] opened 2023-02-07 16:05 UTC
Hi Fahad,

nice work on this library!

When running one of your examples ("Entities API") I get the following error:

> Exception has occurred: CrunchbaseAPIException
> Expecting value: line 1 column 1 (char 0)
> StopIteration: 0
> 
> During handling of the above exception, another exception occurred:
> 
> json.decoder.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> During handling of the above exception, another exception occurred:
> 
> requests.exceptions.JSONDecodeError: Expecting value: line 1 column 1 (char 0)
> 
> The above exception was the direct cause of the following exception:
> 
>   File "C:\...\crunchbase_library_test.py", line 13, in <module>
>     entity = org_api.get(
> py_crunchbase.apis.base.CrunchbaseAPIException: Expecting value: line 1 column 1 (char 0)

Not sure exactly what is causing this but seems to be related to the formatting of the JSON request.

I am using requests version 2.28.2 which meets the requiement value set in requirements.txt

Best Regards,
Sebastian

**Comment by FahadNoor** [comment] 2023-02-07 16:28
Hi @Sebastian-ehrig. Thanks for bringing it up. I've a few meetings in queue. I will try and look into it tomorrow.

**Comment by Sebastian-ehrig** [comment] 2023-02-07 21:52
Hi @FahadNoor thanks for your quick response. 

Here is the code:

`from py_crunchbase import PyCrunchbase, Cards
import requests

print(requests.__version__)

API_KEY = '***************'

pycb = PyCrunchbase(API_KEY)

org_api = pycb.organizations_api()

cards = Cards.Organization
entity = org_api.get(
    entity_id='tesla-motors',
    field_ids=['website', 'facebook', 'categories', 'short_description', 'founded_on', 'rank_org_company'],
    card_ids=[cards.founders, cards.raised_funding_rounds]
)

print(entity.website, entity.cards)`

**Comment by FahadNoor** [comment] 2023-02-08 07:12
Thanks. Can you check if you are using the correct version of `requests` module? Because `version` attribute isn't available in `2.28.2`. It might have been available in the older versions.

<img width="885" alt="Screenshot 2023-02-08 at 12 10 58 PM" src="https://user-images.githubusercontent.com/8684377/217459384-d96228a2-7fb3-470a-afe2-bd10ed6e4129.png">

**Comment by Sebastian-ehrig** [comment] 2023-02-08 08:02
Hi @FahadNoor, that must have been a formatting error when copying the code into the text-field. I was indeed using in my code "requests.__version__". The requests version that I am using is 2.28.2.

<img width="662" alt="image" src="https://user-images.githubusercontent.com/102523524/217469234-4c8ffe90-d4e4-436a-9b10-7bf7990daf3a.png">

**Comment by FahadNoor** [comment] 2023-02-08 13:55
ah, that makes sense. Unfortunately I still haven't been able to reproduce the issue. I've tried with basic and enterprise API key.

Can you run the code through debugger and look at the response/data you are getting from Crunbhase? You should be able to check the value of response and data [here](https://github.com/FahadNoor/py_crunchbase/blob/main/py_crunchbase/apis/base.py#L54).

**Comment by Sebastian-ehrig** [comment] 2023-02-08 18:02
The response data returns: <Response [404]>

**Comment by FahadNoor** [comment] 2023-02-08 19:41
It might be an API key related issue. Can you try with a different key?

**Comment by Sebastian-ehrig** [comment] 2023-02-08 21:14
I don't think it is the API key. I have made a quick test with some simple code which returns 200.

`import requests

api_key = '************************'
base_url = "https://api.crunchbase.com/api/v4/entities/"
company_endpoint = "organizations/"
company_name = "tesla-motors"

query = {
    "card_ids": [
    "founders",
    "raised_funding_rounds"
    ],
  "field_ids": [
   'website',
   'facebook',
   'categories',
   'short_description',
   'founded_on',
   'rank_org_company'
  ],
}

# Build the full API request URL
url = base_url + company_endpoint + company_name + "?user_key=" + api_key

# Send the API request and get the response
response = requests.get(url, params = api_key , json = query)

# Check the status code of the response to make sure it was successful
print('Response: ', response.status_code)`

**Comment by Sebastian-ehrig** [comment] 2023-02-09 14:46
Hi @FahadNoor , I have tried your examples again on a Linux system and there it is working fine! This is perhaps an issue related to windows.

**Comment by FahadNoor** [comment] 2023-02-09 17:49
oh, weird. I will give it a try on Windows. Thanks for sharing this info.

**Comment by alex-tarasov-6669** [comment] 2023-02-15 01:55
@FahadNoor I have the same problem... Could it be because the Starter level of access is being used?
I'll ask here at the same time - do you think there is a way to get data from Signal & News -> Timeline via API?

**Comment by FahadNoor** [comment] 2023-02-15 06:20
Hi @alex-tarasov-6669, this seems to be an issue related to Windows. I haven't got a chance to test it on Windows myself. I will try next week. Can you try on Linux?

As for Signal & News, I am not sure. I would suggest to explore the [organisations API](https://app.swaggerhub.com/apis-docs/Crunchbase/crunchbase-enterprise_api/1.0.3#/Entity/get_entities_organizations__entity_id_) with available cards like ipos, layoffs, event_appearances etc and see if it works for you.

**Comment by alex-tarasov-6669** [comment] 2023-02-15 08:59
@FahadNoor Just tested it on my GCP instance and get: py_crunchbase.apis.base.CrunchbaseAPIException: MD403:  insufficient permissions to read field categories. MD403:  insufficient permissions to search field funding_total
So, probably I may be right about permissions and access level.

`from py_crunchbase import PyCrunchbase, Entities
from py_crunchbase.apis.search.predicates import Currency

pycb = PyCrunchbase('key')
api = pycb.search_organizations_api()

org_facet_ids = Entities.Organization.Facets
api.select(
    'identifier', 'categories', 'location_identifiers', 'short_description', 'rank_org'
).where(
    funding_total__between=[Currency(25000000), Currency(100000000)],
    location_identifiers__includes=['6106f5dc-823e-5da8-40d7-51612c0b2c4e'],
    facet_ids__includes=[org_facet_ids.company]
).order_by(
    'rank_org'
)

for page in api.iterate():
    for company in page:
        print(company.permalink)`

**Comment by FahadNoor** [comment] 2023-02-15 09:20
Oh, when you said that you had the same issue, I assumed it was same as Sebastian. He was getting a 404 on Windows. 
But yes you are right, it seems like an API access/permission issue.

**Comment by FahadNoor** [comment] 2023-03-04 20:58
@Sebastian-ehrig I've fixed this issue in the latest release. I am closing the issue. Feel free to reopen it if you still face the same problem.

**Closed by FahadNoor** 2023-03-04 20:58 UTC
